-- 库函数的中文别名 --
-- chs包--
local CURRENT_MODULE_NAME = chs

IDOK=1
IDCANCEL=2
IDABORT=3
IDRETRY=4
IDIGNORE=5
IDYES=6
IDNO=7
MB_YESNO = 4

NULL = 0

SW_SHOW = 5
SW_HIDE = 0

CSIDL_COMMON_STARTMENU=0x0016			-- All Users\Start Menu
CSIDL_COMMON_PROGRAMS=0X0017			-- All Users\Start Menu\Programs
CSIDL_COMMON_STARTUP=0x0018				-- All Users\Startup
CSIDL_COMMON_DESKTOPDIRECTORY=0x0019	-- All Users\Desktop
